services:
  - type: web
    name: savithahayag-django
    env: python
    plan: free
    rootDir: unified_reasoning_platform
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false